---
# This Playbook deploys jenkins ci!

- hosts: jenkins
  vars_files:
    - vars/main.yml
    - vars/private.yml
  user: root
  roles:
    - {role: nginx, when: jenkins_webserver == 'nginx'}
  tasks:
  - include: tasks/configure-repository.yml
  - include: tasks/install-dependencies.yml
  - include: tasks/install-jenkins.yml

#  handlers:
#   - include: handlers/main.yml
