---

# Configure Jenkins repository

- name: Add jenkins apt-key
  apt_key: url=${jenkinsKey} state=present
  tags:
    - jenkins

- name: Configure apt repository manually to get around missing source repository problem
  copy: src=root/etc/apt/sources.list.d/jenkins.list dest=/etc/apt/sources.list.d/jenkins.list owner=root group=root mode=0755
  tags:
    - jenkins
