---
# Install Jenkins dependencies
- name: Install Jenkins dependencies 
  apt: pkg=$item state=installed update-cache=yes
  with_items:
    - openjdk-7-jdk
    - openjdk-7-jre
  tags: 
    - jenkins
